config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  get 'page/venues'

  get 'page/events'

  get 'page/contact'

  get 'page/photos'

  get 'page/happy_hour'

  get 'page/whats_hot'

  get 'page/near_me'

  get 'page/log_in'

  get 'page/music'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def venues
  end

  def events
  end

  def contact
  end

  def photos
  end

  def happy_hour
  end

  def whats_hot
  end

  def near_me
  end

  def log_in
  end

  def music
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>The Nightlife Company | Omaha</title>
	<%= csrf_meta_tags %>

    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- FancyBox -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.css"/>

    <!-- Custom Stylesheet -->
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/png" href="<%= asset_path "favicon.png" %>" sizes="32x32" />
    <link rel="icon" type="image/png" href="img/icons/favicon.png" sizes="16x16" />
  </head>
  <body>
    <header class="wrapper">
      <nav class="navbar navbar-inverse navbar-static-top container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">NightlifeCo</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="<%= page_home_path %>"><img class="navbar-brand" src="<%= asset_path "logo.png" %>" alt="NightlifeCo"></a>
          <img class="search" src="<%= asset_path "search.png" %>" alt="search" width="20">
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/page/near_me">Near Me</a></li>
            <li><a href="/page/events">Events</a></li>
            <li><a href="/page/music">Music</a></li>
            <li><a href="/page/venues">Venues</a></li>
            <li><a href="/page/photos">Photos</a></li>
            <li><a href="/page/happy_hour">Happy Hour</a></li>
            <li><a href="/page/whats_hot">What's Hot</a></li>
            <li><a href="http://tickets.nightlifeco.com/" target="_blank">Tickets</a></li>
            <li><a href="/page/contact">Contact</a></li>
            <li><a href="<%= page_log_in_path %>">Log In</a></li>
          </ul>
        </div>
      </nav>
      <div class="live-search">
		<i class="close pe-7s-close pe-fw" onclick="hideLiveSearch()"></i>
		<img class="close" src="<%= asset_path "x.png" %>" alt="" width="40">
		<input class="query" type="text" name="query" autocomplete="off">
		<div class="results"></div>
	  </div>
    </header>
	<%= yield %>
    <footer>
      <div class="container text-center">
        <h3>Contact Us</h3>
        <p>4521 Leavenworth Street, Suite 16
Omaha, NE 68123</p>
        <p>402-682-7117</p>
      </div>
      <div class="container text-center text-uppercase">
        <h4>Sign up for our weekly newsletter</h4>
        <form class="newsletter">
          <label>Email</label>
          <input type="email" name="email">
          <a href="#">Subscribe</a>
        </form>
      </div>
      <div class="container">
        <div>© 2017 The Nightlife Company, LLC. All rights reserved.</div>
        <div></div>
      </div>
    </footer>


    <!-- Bootstrap JavaScript CDN-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.js"></script>

  </body>
</html>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/events.html.erb
<h1>Page#events</h1>
<p>Find me in app/views/page/events.html.erb</p>

app/views/page/happy_hour.html.erb
<h1>Page#happy_hour</h1>
<p>Find me in app/views/page/happy_hour.html.erb</p>

app/views/page/home.html.erb
    <section class="hero-img container-fluid">
      <div class="intro text-center">
        <h2><%= @test %> Omaha's Premiere Entertainment Guide</h2>
        <p>Bar and club listings, restaurants, upcoming events, and happy hours.</p>
      </div>
    </section>
    <section class="near-me text-center">
      <header>
        <h3>Finding Events is easy</h3>
        <p>Find an event near you with our map.</p>
      </header>
      <div class="map"></div>
      <a href="/page/near_me" class="cta-button">Find Events</a>
    </section>
    <section class="venues">
      <header>
        <h3 class="text-center">Featured Venues</h3>
      </header>
      <div class="container">
        <div class="row">
          <div class="col-xs-6 f-v-1"></div>
          <div class="col-xs-6">
          	<div>Anthony’s Steakhouse</div>
			<div>7220 F Street</div>
			<div>(402)331-7575</div>
			<div>Hours:</div>
			<div>M-Th: 11:00 AM-10:00 PM</div> 
			<div>F-S: 11:00 AM-11:00 PM</div>
			<div>Closed: Sun</div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-xs-6 f-v-1"></div>
          <div class="col-xs-6">
          	<div>Bar 415</div>
			<div>415 S 13th St</div>
			<div>(402)346-7455</div>
			<div>Hours:</div>
			<div>T-S: 8:00 PM-2:00 AM</div> 
			<div>Closed: Sun-Mon</div>
          </div>
        </div>
        <div class="container text-center"><a href="/page/venues" class="cta-button">More Venues</a></div>
      </div>
    </section>
    <section>
      <header>
        <h3 class="text-center">Upcoming Events</h3>
      </header>
      <div class="container">
        <div class="row">
          <a href="" class="">
          	<div class="col-xs-6 f-v-1">
          		<div>March 31</div>
          		<div>9pm</div>
          	</div>
          </a>
          <a href=""><div class="col-xs-6 f-v-1"></div></a>
        </div>
      </div>
       <div class="container">
        <div class="row">
          <div class="col-xs-6"></div>
          <div class="col-xs-6"></div>
        </div>
      </div>
       <div class="container">
        <div class="row">
          <div class="col-xs-6"></div>
          <div class="col-xs-6 text-center"><a href="/page/events" class="cta-button">Upcoming Events</a></div>
        </div>
      </div>
    </section>
    <section>
      <header>
        <h3 class="text-center">Today's Happy Hours</h3>
      </header>
       <div class="container-fluid text-center">
         <div class="col-sm-1">
         	<a data-fancybox="gallery" href="big_1.jpg" class="hpy-hr-home"><div>7M Grill</div></a>
         </div>
         <div class="col-sm-1 hpy-hr-home">
         	<a data-fancybox="gallery" href="big_1.jpg" class="hpy-hr-home"><div>Bar 415</div></a>
         </div>
         <div class="col-sm-1 hpy-hr-home">
         	<a data-fancybox="gallery" href="big_1.jpg" class="hpy-hr-home"><div>Ozone Lounge</div></a>
         </div>
         <div class="col-sm-1"><a href="/page/happy_hour" class="cta-button">More Happy Hours</a></div>
      </div>
    </section>
    <section>
      <header>
        <h3 class="text-center">Recent Photos</h3>
      </header>
        <div class="container">
          <div class="row">
            <div class="col-md-1"></div>
            <div>
              <p class="col-xs-6">asdfasdf</p>
              <p class="col-xs-6">asdlfjsadofs</p>
            </div>
          </div>
        </div>
      <div class="text-center"><a href="/page/photos" class="cta-button">More Photos</a></div>
    </section>
    <section class="container text-center">
      <header>
        <h3>Advertise with us</h3>
      </header>
      <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent laoreet nibh id finibus convallis. Sed et dapibus lectus. Ut vestibulum nisi ac sapien auctor lacinia. Donec efficitur sem vel tortor placerat posuere. Cras lectus urna, aliquet in.</p>
        <a href="/page/contact" class="cta-button">more info</a>
      </div>
    </section>

app/views/page/log_in.html.erb
<h1>Page#log_in</h1>
<p>Find me in app/views/page/log_in.html.erb</p>

app/views/page/near_me.html.erb
<h1>Page#near_me</h1>
<p>Find me in app/views/page/near_me.html.erb</p>

app/views/page/photos.html.erb
<h1>Page#photos</h1>
<p>Find me in app/views/page/photos.html.erb</p>

app/views/page/venues.html.erb
<div>
	<div></div>
	<div></div>
	<div></div>
</div>

app/views/page/whats_hot.html.erb
<h1>Page#whats_hot</h1>
<p>Find me in app/views/page/whats_hot.html.erb</p>